name: OpenWrt Build

on:
  schedule:
    # At the end of every day
    - cron: '0 0 * * *'
  push:
    branches:
      - main
      - tmp
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  release:
    types: [created]

jobs:
  build:
    name: ${{ matrix.arch }} ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm_cortex-a9_vfpv3-d16
            target: mvebu-cortexa9

          - arch: arm_cortex-a15_neon-vfpv4
            target: armvirt-32

          - arch: x86_64
            target: x86-64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-snapshot
          FEED_DIR: ${{ github.workspace }}/packages/openwrt
          FEEDNAME: ndpid_openwrt_packages_ci
          PACKAGES: nDPId-testing
          V: s

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: nDPId-${{ matrix.arch}}-${{ matrix.target }}
          path: bin/packages/${{ matrix.arch }}/ndpid_openwrt_packages_ci/*.ipk
